name: ci

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build Solution (x64)
      run: msbuild "-p:Configuration=Release;Platform=x64;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln
    - name: Build Solution (ARM64)
      run: msbuild "-p:Configuration=Release;Platform=ARM64;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln
      # Win32 built last
    - name: Build Solution (Win32)
      run: msbuild "-p:Configuration=Release;Platform=Win32;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln

    - name: Upload everything to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Everything
        path: .\bin\Release\**\*.*
    - name: Upload ThemeTool to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ThemeTool
        path: |
          .\bin\Release\Win32\ThemeTool.exe
          .\bin\Release\Win32\ThemeTool.pdb
